In [4]:
import pandas as pd

restaurants = pd.read_csv('restaurants.csv')

restaurants

del restaurants['menus.amountMax']
del restaurants['menus.amountMin']

restaurants.to_csv('restaurants.csv')

In [39]:
import numpy as np

empty_df = []
empty_df_y = []
training_df = []
training_df_y = []
cur_row = []
columns = [
    'postalCode',
    'restaurant_count',
    'taco_ratio',
    'meat_ratio',
    'seafood_ratio',
    'vegetarian_ratio',
    'breakfast_ratio',
    'other_ratio',
]
for index, row in restaurants.iterrows():
    if len(str(row['postalCode'])) > 5:
        row['postalCode'] = str(row['postalCode'])[0:5]
    cur_row = [
        row['postalCode'],
        row['restaurant_count'],
        row['taco_ratio'],
        row['meat_ratio'],
        row['seafood_ratio'],
        row['vegetarian_ratio'],
        row['breakfast_ratio'],
        row['other_ratio'],
    ]
    
    if not pd.isna(row['priceRangeCategory']):
        training_df.append(cur_row)
        training_df_y.append(row['priceRangeCategory']) 
    else:
        empty_df.append(cur_row)

for i in reversed(range(len(training_df))):
    for item in training_df[i]:
        if pd.isna(item):
            training_df.pop(i)
            training_df_y.pop(i)

training = pd.DataFrame(training_df,columns=columns)
empty = pd.DataFrame(empty_df,columns=columns)

training

postalCode  restaurant_count  taco_ratio  meat_ratio  seafood_ratio  \
0          90048                49    0.454545    0.545455       0.000000   
1          60010                 1    0.500000    0.000000       0.000000   
2          94611                 2    0.241379    0.000000       0.206897   
3          36832               152    0.000000    0.500000       0.000000   
4          12309                 1    1.000000    1.000000       0.000000   
5          85326              1991    0.000000    1.000000       0.000000   
6          96761                 1    1.000000    0.000000       1.000000   
7          29928                 1    1.000000    1.000000       0.000000   
8          91502                 1    1.000000    0.000000       1.000000   
9          53202                 1    0.000000    0.000000       0.000000   
10          6811                 1    0.000000    0.000000       0.000000   
11         43026                 1    0.000000    0.000000       0.000000   
12         11730                 1    0.000000    1.000000       0.000000   
13          3079               157    0.714286    0.238095       0.000000   
14         55418                 1    0.000000    0.000000       0.000000   
15         33441                 1    0.000000    0.333333       0.000000   
16         73103                 1    0.000000    1.000000       0.000000   
17         75965              1137    1.000000    1.000000       0.000000   
18         95110               278    0.500000    0.250000       0.500000   
19          6473              1991    0.000000    1.000000       0.000000   
20         47803               470    0.000000    0.400000       0.000000   
21         22310                 1    1.000000    0.500000       0.000000   
22         60007              1991    0.000000    1.000000       0.000000   
23         60642                 1    0.714286    0.285714       0.000000   
24         91702                 1    0.666667    0.400000       0.000000   
25         33409                97    1.000000    0.000000       1.000000   
26         95014                16    0.500000    0.300000       0.200000   
27         62704                 1    1.000000    0.000000       1.000000   
28         96761                 6    0.333333    0.000000       0.000000   
29         97123                 1    1.000000    1.000000       0.000000   
...          ...               ...         ...         ...            ...   
10621      46809               157    1.000000    0.000000       1.000000   
10622      76034              1991    0.000000    1.000000       0.000000   
10623      85143              1137    1.000000    1.000000       0.000000   
10624      78204              1137    1.000000    1.000000       0.000000   
10625      10019                 3    0.200000    0.200000       0.000000   
10626      91350                 8    1.000000    0.000000       0.000000   
10627      62701                 1    0.000000    0.000000       0.000000   
10628      67042               470    0.000000    0.400000       0.000000   
10629      81301                 1    0.750000    0.250000       0.000000   
10630       6511                 1    0.333333    0.500000       0.000000   
10631      96756                 1    1.000000    1.000000       0.000000   
10632      92037                 1    0.750000    0.250000       0.250000   
10633      77006                 2    1.000000    0.500000       0.500000   
10634      60654                 1    1.000000    0.000000       1.000000   
10635      76107                 2    0.666667    0.666667       0.333333   
10636      76148                 2    0.000000    0.000000       0.000000   
10637      75287                 1    0.000000    1.000000       0.000000   
10638      75226                 2    1.000000    0.666667       0.166667   
10639      75234                 2    0.000000    1.000000       0.000000   
10640      75230                 2    1.000000    0.333333       0.666667   
10

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(training_df, training_df_y, random_state=0)
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [42]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(X_train, y_train)
print('Accuracy of GNB classifier on training set: {:.2f}'
     .format(gnb.score(X_train, y_train)))
print('Accuracy of GNB classifier on test set: {:.2f}'
     .format(gnb.score(X_test, y_test)))

Accuracy of GNB classifier on training set: 0.41
Accuracy of GNB classifier on test set: 0.40


In [43]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
print('Accuracy of Logistic regression classifier on training set: {:.2f}'
     .format(logreg.score(X_train, y_train)))
print('Accuracy of Logistic regression classifier on test set: {:.2f}'
     .format(logreg.score(X_test, y_test)))

Accuracy of Logistic regression classifier on training set: 0.66
Accuracy of Logistic regression classifier on test set: 0.65


/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [44]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier().fit(X_train, y_train)
print('Accuracy of Decision Tree classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print('Accuracy of Decision Tree classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of Decision Tree classifier on training set: 0.99
Accuracy of Decision Tree classifier on test set: 0.66


In [45]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
print('Accuracy of K-NN classifier on training set: {:.2f}'
     .format(knn.score(X_train, y_train)))
print('Accuracy of K-NN classifier on test set: {:.2f}'
     .format(knn.score(X_test, y_test)))

Accuracy of K-NN classifier on training set: 0.78
Accuracy of K-NN classifier on test set: 0.69


In [46]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis()
lda.fit(X_train, y_train)
print('Accuracy of LDA classifier on training set: {:.2f}'
     .format(lda.score(X_train, y_train)))
print('Accuracy of LDA classifier on test set: {:.2f}'
     .format(lda.score(X_test, y_test)))

Accuracy of LDA classifier on training set: 0.65
Accuracy of LDA classifier on test set: 0.64


/anaconda3/lib/python3.7/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


In [47]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(X_train, y_train)
print('Accuracy of SVM classifier on training set: {:.2f}'
     .format(svm.score(X_train, y_train)))
print('Accuracy of SVM classifier on test set: {:.2f}'
     .format(svm.score(X_test, y_test)))

/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


Accuracy of SVM classifier on training set: 0.68
Accuracy of SVM classifier on test set: 0.67


In [48]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
pred = knn.predict(X_test)
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[831 361   3]
 [260 999  28]
 [ 26 140  15]]
              precision    recall  f1-score   support

         1.0       0.74      0.70      0.72      1195
         2.0       0.67      0.78      0.72      1287
         3.0       0.33      0.08      0.13       181

   micro avg       0.69      0.69      0.69      2663
   macro avg       0.58      0.52      0.52      2663
weighted avg       0.68      0.69      0.68      2663

